### PR TITLE
fix: add all files for LightningComponentBundle

### PR DESCRIPTION
**Pull request by leboff**
Fixes issue with LightningComponentBundles so all files from the bundle are added to package when one file is changed (similar to Aura bundles)

### CODE REVIEW

**Comment by leboff** [comment]
Should work now right? Or does the commit message need to be updated too?

**Comment by amtrack** [comment]
yes, I think that’s fine now.

**Comment by leboff** [comment]
@amtrack I don't think that worked (according to the deploy log)

**Comment by amtrack** [comment]
@leboff oops! That happened to me before. I should have known :-/
I (kind of) resolved it last time by creating an entry commit with the correct message: https://github.com/amtrack/force-dev-tool/commit/0d8e06cd2a229dc760b4f5716289a13b3a332f94

**Comment by leboff** [comment]
that worked. released now. Thanks!

**Pull request merged**
