### PR TITLE
added two dependencies needed to run.

### PR DESCRIPTION
**Pull request by ckoppelman**

### CODE REVIEW

**Comment by amtrack** [comment]
@ckoppelman Can you describe the problem/error you're getting without this patch?
What operating system / node version are you running?

I can see that both "is-my-json-valid" and "hawk" are being installed as dependencies of other packages i'm using. So there shouldn't be a need to install them explicitly as far as i know.

**Comment by ckoppelman** [comment]
On my OSX Mavericks / npm v3.3.9, I was getting an issue where npm was trying to move those packages before they were installed.  I couldn't run force-dev-tool --help until I installed those packages separately.

**Comment by amtrack** [comment]
That's strange, i'm running the same version of npm on OS X El Capitan and don't have any problems with those packages.
Could you maybe try the following and see if the issue still occurs?

```console
npm uninstall -g force-dev-tool
npm cache clean
npm install -g force-dev-tool
```

I hope you understand that i don't feel comfortable adding packages to my package.json which i'm not using directly...

**Comment by ckoppelman** [comment]
That worked.  Odd.  I totally understand your concerns.  I'd have had the same.

**Comment by amtrack** [comment]
Cool! I'm glad it worked!
If you have any other questions, problems or ideas, don't hesitate to open an issue or ping me.

**Pull request closed without merging**
